# original from https://github.com/pamubay/hugo-builder-theme
# hugo -b build:main.scss --gc --config buildconfig.toml -d static

baseURL = "http://example.org/"
languageCode = "en-us"
title = "Use ONLY for building theme assets"

defaultContentLanguage = "cli"
archetypeDir = "_tmp"
publishDir = "_tmp"
staticDir  = "_nodir"
contentDir = "_tmp"
ignoreFiles = [".*"]
disableKinds = ["section","taxonomy","taxonomyTerm","RSS","404","sitemap"]

[outputs]
  home = ["CLI"]

[mediaTypes."text/custom"]
  suffixes = [""]
  delimiter = ""

[outputFormats."CLI"]
  mediaType = "text/custom"
  isHTML = "false"
  baseName = "hugo.log"

