baseURL = "/"
languageCode = "en-us"
title = "Pointy's"

# Only use if exampleSite is inside theme folder
#themesDir = "../../"

#theme = "pointyfood"
paginate = 8

#sectionPagesMenu = "main"

[[menu.main]]
  name = "Attributions"
  title = "Attributions"
  weight = 100
  identifier = "attributions"
  url = "/attributions/"

[[menu.main]]
  name = "About"
  title = "About the Author"
  weight = 110
  identifier = "about"
  url = "/about/"

[[menu.main]]
  name = "Recipes"
  title = "Recipes and Food Section"
  weight = 120
  identifier = "food"
  url = "/food/"

[[menu.main]]
    name = "Lorem"
    title = "Lorem Ipsum"
    weight = 130
    identifier = "lorem"
    url = "/lorem/"

[params]
  copyright = "© 2018 PointyFar"
  subtitle = "Blog Template for Hugo"
  mainSections = ["food", "post", "wonderland"]
  
  socialdata = "social"
  
[params.scss]
  customFontBody = "Georgia,Utopia,Charter,serif"
  brandFont = "'Oswald', sans-serif"
  primary = "CadetBlue"
  primaryInvert = "#fff"
  
  footnote = "FOOTNOTE:"
  
[params.hero]
  #background = "img/hero-background.jpeg"
  background = "img/hero-background-dark.jpeg"
  #background = "img/hero-background-light.jpeg"
  bgislight = false

[params.author]
  name = "Pointy Far"
  short = "Pointy"
  photo = "img/hello.jpeg"
  header = "Howdy!"
  blurb = " This is params author blurb. Configure me! \
            Possumus quorum aliqua aut anim ut eiusmod exquisitaque ut consequat. \
            O id sempiternum, voluptate quo ingeniis. \
            Duis ab et nulla incurreret, litteris qui possumus."
  aboutSection = "/about/"

[params.subnav]
  usetaxonomy = "tags"
  taxonomycount = 3
  featuredterms = ["queen"]
  
  
  
[params.footer]
  left = ["footerlinks", "otherlinks", "footerlinks"]
  right = ["copyright", "footertext", "footerimage"]
  
  